### ISSUE TITLE
Adding a sound effect

### ISSUE THREAD

**Issue by good777LUCKY** [llama-development/FriendSystemNK#1]
Can you add a sound effect for this plugin? For example, when player's friend join plugin will play a sound. And when someone request friend then it will play a sound like "random.levelup". And I think it would be more useful if I could set all the sound effects in "config.yml".

**Comment by Mundschutziii** [comment]
That would be a good idea, maybe this will be included in one of the next updates.

**Comment by good777LUCKY** [comment]
Cool!

**Comment by Mundschutziii** [comment]
Your proposal is now being implemented. An update will be released soon.
