### ISSUE TITLE
Can you support multi languages?

### ISSUE THREAD

**Issue by good777LUCKY** [llama-development/FriendSystemNK#5]
Can you support multi languages? Like EssentialNK (https://github.com/SupremeMortal/EssentialsNK/tree/master/src/main/resources/lang) like this.

**Comment by Mundschutziii** [comment]
You can change everything in the message.yml.

**Comment by good777LUCKY** [comment]
i know but it will be easy to contribute languages

**Comment by good777LUCKY** [comment]
because message.yml is just one file

**Comment by ProxmaDev** [comment]
Yeah, you can edit there everything. Also, please stop creating so many issues.

**Comment by good777LUCKY** [comment]
i was talking about

resources
|_ lang
  |_ eng.yml
  |_ deu.yml
  |_ kor.yml
    ...

like this.
It will be easy to contribute languages and contributor will not have to create fork versions.

**Comment by good777LUCKY** [comment]
> Yeah, you can edit there everything. Also, please stop creating so many issues.

I was just creating issue for some enchantment, sorry for annoying issues. Is there way to submit things without github issue?

**Comment by ProxmaDev** [comment]
We will not add this because if one translater doesn't translate anymore the language file will be useless. Everything is in english. Most of the people understand english, so they can edit it how they need it.

**Comment by ProxmaDev** [comment]
> > Yeah, you can edit there everything. Also, please stop creating so many issues.
> 
> I was just creating issue for some enchantment, sorry for annoying issues. Is there way to submit things without github issue?

You can post it on our discord for example. Or post it below your already created issues.

**Comment by good777LUCKY** [comment]
> > > Yeah, you can edit there everything. Also, please stop creating so many issues.
> > 
> > 
> > I was just creating issue for some enchantment, sorry for annoying issues. Is there way to submit things without github issue?
> 
> You can post it on our discord for example. Or post it below your already created issues.

Thank you for replying this question. Thanks.
